// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------------------- //
// i2s_tda1543_stereo_on_demand //
// ---------------------------- //

#define i2s_tda1543_stereo_on_demand_wrap_target 0
#define i2s_tda1543_stereo_on_demand_wrap 12

static const uint16_t i2s_tda1543_stereo_on_demand_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 2     
    0xb847, //  1: mov    y, osr          side 2     
    0xb0e2, //  2: mov    osr, y          side 0     
    0xb442, //  3: nop                    side 1     
    0xf02e, //  4: set    x, 14           side 0     
    0x7001, //  5: out    pins, 1         side 0     
    0x1445, //  6: jmp    x--, 5          side 1     
    0x98a0, //  7: pull   block           side 2     
    0xbc42, //  8: nop                    side 3     
    0xf82e, //  9: set    x, 14           side 2     
    0x7801, // 10: out    pins, 1         side 2     
    0x1c4a, // 11: jmp    x--, 10         side 3     
    0x1800, // 12: jmp    0               side 2     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_tda1543_stereo_on_demand_program = {
    .instructions = i2s_tda1543_stereo_on_demand_program_instructions,
    .length = 13,
    .origin = -1,
};

static inline pio_sm_config i2s_tda1543_stereo_on_demand_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_tda1543_stereo_on_demand_wrap_target, offset + i2s_tda1543_stereo_on_demand_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif
